name: 'pub_dev_client'
description: 'A Pub Client For Interact with pub.dev api easly'
version: '0.0.5'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/azkadev/pub_dev_client'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.56'
  http: '^1.2.2'
  io_universe: '^0.0.4'
  oauth2: '^2.0.3'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
